<?php

namespace AppBundle\Repository;

/**
 * CategorieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorieRepository extends \Doctrine\ORM\EntityRepository
{

    public function CategQuery(){
    $query = $this->createQueryBuilder('categorieAlias')
    ->select('categorieAlias.name')
    ->getQuery()
    ->getSingleResult()
    ->getResult()
    ;
    return $query;
    }
}
