<?php

namespace AppBundle\Repository;

/**
 * LivreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LivreRepository extends \Doctrine\ORM\EntityRepository
{

    public function testQuery(){
        /*
        *createQueryBuilder : constructeur de requêtes
        *definir l'alias de l'entité
        *méthodes reprennent le nom des commandes SQL
        *    select : choix des propriétés de l'entité en utulisant l'alias / renvoie un array de array 
        *    where/ andWhere / orWhere : utilisation de where en première condition / A partir de la deuxième condition : utilisation de andWhere ou orWhere
        *    utilisation des paramètres de requête
        *
        *getQuery: execution de la requete / ppe de cette méthode en avant-dernière position
        *récupération des résultats : dernièere position
        *   getresult : renvoie un array d'objets
        */
        $query = $this->createQueryBuilder('livreAlias')
        ->select('livreAlias.name, livreAlias.slug')
        ->getQuery()
        ->getSingleResult()
        //->getResult()
        ;

        //requete de regroupement
            $query =$this->createQueryBuilder('livreAlias')
            ->getQuery()
            ->getResult()


            ;

        //retour des resultats
    return $query;
    }
   
}
